# Generated by Django 4.2.6 on 2023-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codebin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pastetitle', models.CharField(max_length=200)),
                ('pastecontent', models.CharField(max_length=200)),
                ('sid', models.IntegerField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
            ],
        ),
    ]
