# Generated by Django 4.1.12 on 2023-10-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebin', '0002_alter_codebin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebin',
            name='visibility',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
